### ISSUE TITLE
infra/module/setup prevents creation when there is no existing k8s configuration

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/datacube-k8s-eks#50]
This setup module has broken the "start from nothing" scenario:
* Add setup module to infrastructure to apply required k8s manifests.

Terraform cannot check the state from k8s without a valid kubeconfig - which you can't have if you don't have a cluster yet or (possibly worse its pointing at another k8s cluster).
 you get a weird looking http://localhost.....aws-auth... access error.

The module is dependent on the existence of k8s and the kubeconfig but there is no dependency put in for.

Personally I think this setup should be moved out of the infra section.

**Comment by woodcockr** [comment]
After further debugging this would appear to be a user error relating to left over invalid state.

**Comment by lbodor** [comment]
I think that this is a real issue. The approach taken on line

https://github.com/opendatacube/datacube-k8s-eks/blob/c75d5989f3ce63d433f3dcd40dcefc8c10e77574/infra/modules/setup/main.tf#L2

seems to rely on the conditional expression being strict in all arguments, which is [no longer the case](https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements) since terraform 0.12. Perhaps initialising the kubernetes provider as described [here](https://github.com/sl1pm4t/terraform-provider-kubernetes/issues/47#issuecomment-417382914) would work and also fix #70.

There is [indication](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types) that terraform 0.12 supports entire resources being used as module inputs and output.
